server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # React Router — trả về index.html cho mọi route
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy /api sang gateway
    location /api {
        proxy_pass http://gateway-service:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
